version: '3.2'

services:
  filebeat:
    container_name: filebeat
    hostname: filebeat
    user: root
    image: docker.elastic.co/beats/filebeat:7.12.0
    volumes:
      #Mount the filebeat configuration so users can make edit
      - ./fb_config:/usr/share/filebeat/filebeat.yml
      #Mount the hosts system log directory. This represents the logs of the VM hosting docker. Consumed by the filebeat system module.
      - /var/log/:/var/log/